### ISSUE TITLE
User Profile experience in chapters is inconsistent

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#29]
Example:
https://europe-womeninidentity.silkstart.com/myprofile/edit shows information about the user, but https://europe-womeninidentity.silkstart.com/myprofile/detailed shows "Page Not Found".

**Comment by fhobswid** [comment]
Given that Country of Residence is a mandatory field, this should be nearer the top.

Editing profile in chapter that you're not part of doesn't work, but this isn't clear when you begin the journey. I.e. I could be in Americas (which I'm not a part of) and edit everything in my profile, but when I go to save it it will not work. If we don't allow people to edit profile in chapter, they shouldn't be able to get to this point.

**Comment by pamelatech** [comment]
Reviewed with Michael 8/16, this fix is in the pipeline, and should address the initial report and Francesca's second observation

**Comment by mcresilkstart** [comment]
@hlflanagan @pamelatech the fix for this has now been released.  I checked it on our staging environment before release and it looked good.  Please check it now on your site.

**Comment by hlflanagan** [comment]
Verified - thanks!
