### ISSUE TITLE
Can jobs/events/articles content from one chapter/apex appear in another chapter widget?

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#37]
E.g. Could Apex Articles appear in 'Recent Posts' widget on Americas homepage?

Otherwise we have to remove and replace various widgets before launch. This makes it urgent.

**Comment by hlflanagan** [comment]
Right now, the widget will only show what's populated in the chapter.

**Comment by fhobswid** [comment]
This is currently my most pressing issue. If it's not possible, I will need to change all of the homepages.
Would be great to get your input @mcresilkstart - thank you

**Comment by mcresilkstart** [comment]
@fhobswid I have checked this with the product team and currently this is not possible (to show recent articles for example in a widget in another chapter).
