### ISSUE TITLE
How to move header text (on banner) higher on Silkstart app pages - e.g. Jobs, Campaigns?

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#38]

**Comment by mcresilkstart** [comment]
@fhobswid I have added some new CSS to the APEX custom CSS section that moves the text on the header higher for both the donation list page and the jobs board page.  You can replicate elsewhere as needed as long as you find the name of the application page where you want this to change.  You can find this name if you 'inspect' the HTML page.
