### ISSUE TITLE
Sponsors page background has header step and repeat

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#39]
Something seems to have happened to the sponsors page, potentially related to a fix elsewhere?
https://womeninidentity.silkstart.com/sponsors_page
Thanks

**Comment by mcresilkstart** [comment]
@fhobswid oops - I broke something making another change.  Is it ok now?  If so please close this one

**Comment by fhobswid** [comment]
Yes that looks ok now, thanks!
