### ISSUE TITLE
Mailing list subscription text

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#40]
This text needs to be more clear on exactly what the user is subscribing to:

"Please subscribe to our mailing list. After you complete the membership registration, you can control your opt-in and opt out choices in the Communications Settings section of your profile "

We need to be clear as to whether they are subscribing to the general newsletter, to all mailing lists, or to the general newsletter and chapter-specific topics.

**Comment by mcresilkstart** [comment]
@hlflanagan ok it uses this text in your comment right now - so what do you want it to be changed to?

**Comment by hlflanagan** [comment]
The text in the Join Up journey has to be explicit as to exactly what the user will subscribe to if they click that box. If clicking that box results in having the user subscribed to newsletters, announcements, upcoming events,  Everything posted, Changes to jobs I've posted, Posts by people or topics I follow, Posts in discussions I'm involved in, Things I post, and Messages I receive from others users, then we need to say that.

**Comment by mcresilkstart** [comment]
@hlflanagan I am double checking the following but this is what I believe happens with the subscribe process.  The tick box in the sign up process for someone to consent to being a subscriber means they are subscribing to all 'marketing' email campaigns  that you may subsequently send out like a monthly newsletter.  When you plan such an email campaign you can filter the recipient list based on that 'subscriber' status and thus control who the emails go out to.  In addition to this general 'subscriber' status a user can give consent (not in the signup process) to subscribe to specific topics (note that signing up as a subscriber does not subscribe a user to any subscription topics - you have to do that explicitly outside of the signup process) . Again you then control who receives marketing emails for these topics by adding filters based on who has subscribed to each specific topic.

So maybe the existing wording for the signup subscribe tick box info should be:  

Please subscribe to our mailing list. After you complete the membership registration, **you can make more specific mailing list subscription topic choices** in the Communications Settings section of your profile "

**Comment by hlflanagan** [comment]
![image](https://user-images.githubusercontent.com/4659093/130086714-9fadfe3f-0747-465d-80c5-3704c247748e.png)

Note that the "News and Announcements" button is the master button that acts as a subscribe/unsubscribe all. @pamelatech , can you test, please?

**Comment by pamelatech** [comment]
Hi Michael - we have new agreed upon text that better describes what our users are subscribing to.  Can you please change the Join Now subscription box to show this text:

"Please subscribe to receive our newsletter and occasional announcements. You can change your subscription preferences at any time in the Communications Settings section of your profile."

**Comment by pamelatech** [comment]
Turns out there is no "Communications Settings" section in the profile, so can  you use this more accurate text: 

"Please subscribe to receive our newsletter and occasional announcements. You can change your subscription preferences at any time in the Settings section of your profile, under the Communications Preferences tab."

**Comment by hlflanagan** [comment]
Done
