### ISSUE TITLE
ToS and Disclaimer

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#42]
A link to the “Terms of Service” and “Disclaimer” should also be added to the “Legal” section at the bottom of the home page just like the privacy policy is linked in the same section. (see DPIA folder in Google Drive's Silkstart 2021)

**Comment by hlflanagan** [comment]
Pending sign-off on the text; Debbie will let us know

**Comment by pamelatech** [comment]
Link is updated and propagated to all chapters.  Remaining task before launch is to replace Website Disclaimer text with final approved text.  Assigning to @hlflanagan  to finish up

**Comment by hlflanagan** [comment]
Privacy Policy, ToS, and Disclaimer text updated on the new site
