### ISSUE TITLE
Need to build segment lists for email campaigns

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#45]
**Is your feature request related to a problem? Please describe.**
We need to build all the segment lists (e.g., newsletter, announcements) for the site before go-live

**Describe the solution you'd like**
We need to be clear on what users are likely to receive vi email. 

Related to Issue 40

**Comment by mcresilkstart** [comment]
@hlflanagan @pamelatech right I have done some more research in to how subscriptions work and it is a bit different to what I shared in our call on Thursday.  So this is how it works:
**Mailing List subscriber status** (this is the one that you tick in the signup page) - this defaults to 'not subscribed' for any new user that is added.  A user can change this in their preference or by ticking the box in signup to change this to 'subscribed' or 'unsubscribed'.  When you run an email campaign to specify a list of recipients either as a list of names or by selecting a segment list.  When you run the campaign SilkStart will AUTOMATICALLY exclude all recipients whose subscriber status is set to 'unsubscribed' (but it will send to all with the status of 'subscribed' or 'not subcribed' as stated in FAQ: https://silkstartsupport.zendesk.com/hc/en-us/articles/218820467-How-do-I-manage-my-Subscribers-in-SilkStart-

Subscription Topics - users can subscribe to specific topics and each of these are independent from each other and independent of the 'mailing list' subscription discussed above (so think of the mailing list subscription as an initial topic and then other topics can be added but they all work independently.).  WHen you create an email campaign you have an option in the page where you specify recipients to name one or more subscription topics.  So let's say you have a newsletter topic setup and select this on the campaign recipient page then when you send the email campaign it will go to all those users who have signed up to that newsletter topic.  NOTE that the mailing list subscriber status is completely ignored and the only thing that is checked is the user's newsletter topic subscription status.

I hope that now is a lot clearer for you.  Based on this new information then you no longer have to build in specific subscription status filters into a segment list (although it does allow you to do that if you ever wanted to).

**Comment by pamelatech** [comment]
I've edited the Newsletter segment list to have the following two filters:

- Subscription Topic is "Monthly Women in Identity Newsletter"
- Subscribed is "Subscribed" 

I think this covers our needs, it should mean that you only get the newsletter if you have subscribed to it and if you have not Unsubscribed from everything.  Tests in Testpad will be set up right now,  with 4 users:
1) A user who is subscribed to the newsletter subscription topic and has not unsubscribed all
2) A user who is unsubscribed to the newsletter but subscribed generally
3) A user who is subscribed to the newsletter but has unsubscribed to all
4) A user who is unsubscribed to both the subscription topic and the general tickbox

The only user who should get the newsletter is user 1 when we use the segment list.  I will close this issue when my tests prove the segment list is working.


![image](https://user-images.githubusercontent.com/2591320/132098187-f4caa7ab-70ce-4cc4-a507-cc75b7491677.png)
