### ISSUE TITLE
All users should be able to unsubscribe without logging in

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#46]
We need to ensure a non gated Unsubscribed link is hard baked into our email footer that sits on the outside of the email.   There is one in there now but it seems to go to a dead link  https://europe-womeninidentity.silkstart.com/silkcon/unsub?email=-customer-id-&token=-token-

There are many reasons for ensuring we put the word Unsubscribed and have it ungated (not behind a login screen):
- We adopt GDPR best practices
- It will help with our email reputation / spam score so that less email will end up being filtered as junk/spam by Google
- Anyone should be able to unsubscribe whether a member or a supporter

**Comment by mcresilkstart** [comment]
@fhobswid a subscriber can unsubscribe from all emails or for specific topics by clicking on the link in the email footer.  That link should take you to a page where you can make these unsubscribe choices.  See this article for details: https://silkstartsupport.zendesk.com/hc/en-us/articles/212947258-How-does-a-member-unsubscribe-from-emails-

I will test it to make sure it is working for your network.

**Comment by pamelatech** [comment]
It looks like contacts can unsubscribe without logging in.  Members are required to login as far as my testing shows.

Here is the Contact page shown when you click the unsubscribe link:

![image](https://user-images.githubusercontent.com/2591320/132240121-a4bd7d90-bd10-4d40-aed2-014001037e7c.png)

**Comment by mcresilkstart** [comment]
@fhobswid so is there still an issue here then?  I would expect that a member should first login to change their subscription settings for security reasons.

**Comment by fhobswid** [comment]
@mcresilkstart I think @pamelatech has followed this issue more closely so will be better placed to advise

**Comment by mcresilkstart** [comment]
@pamelatech please see my comment above regarding members needing to login to unsubscribe - I would think this is a good security approach to force a member to login to change subscription settings in the same way they need to do that to change any other element of their account.  What's you view on this?

**Comment by hlflanagan** [comment]
We're good on this for now. If it becomes an issue when we undergo a privacy audit, we'll adjust.
