### ISSUE TITLE
The "Events" icon on the Home/Apex page points to the wrong place

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#47]
**Describe the bug**
The Events icon on the Home/Apex page point to the Apex events page and not the Global event page

**What kind of user are you?**
Admin

**To Reproduce**
1. Go to 'https://womeninidentity.silkstart.com/cpages/home'
2. Click on the Events icon mid-page
3. This takes you to https://womeninidentity.silkstart.com/events

**Expected behavior**
This should take you to https://global-womeninidentity.silkstart.com/events

(This is the cross-chapter problem)

**Comment by hlflanagan** [comment]
@fhobswid is this something you can help fix, or do we need Michael?

**Comment by hlflanagan** [comment]
Will need to replace the widget with a custom something.

**Comment by fhobswid** [comment]
I've fixed it now - thanks!
