### ISSUE TITLE
Need a generic event icon

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#48]
** Describe the Bug **
Events with icons look much more attractive than events without them - we need a WID-styled generic event icon that we can attach in cases where the event itself does not have anything we can use.  This is also something we can use for our internal events.  As an example here is a set of 3 external events, one that does not have an icon:

** Describe who you are **
All users including anonymous visitors see these events and we want to have our calendar be a commonly visited event calendar.

**Expected behavior**
At minimum, an attractive icon that fits our color scheme and depicts an event in some easy-to-understand way should be available for events coordinators to use

Best case we might want to create a set of icons that make it easy to tell the difference between different kinds of internal events such as webinars, meetups, or coffee breaks.

**Screenshots**
![image](https://user-images.githubusercontent.com/2591320/132100848-b5f4ea4f-fbe4-4d65-8668-998fe199570c.png)

**Comment by fhobswid** [comment]
Hi - I enlisted Hollie's help and she has come up with a great set of branded icons for each category. Are you happy with these @pamelatech?

Icons here: https://drive.google.com/drive/u/2/folders/1iLuMDd-E39IrvlihkbPsunF3EzjRsC0m

Key here:
![Screenshot 2021-09-16 at 10 27 55](https://user-images.githubusercontent.com/88625230/133590767-fd87ebe4-738d-48ae-a890-4366d71f8867.png)
