### ISSUE TITLE
Missing Internal Documentation site

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#50]
**Describe the bug**
WID internal staff need to know how to maintain the website and use the content.  This needs to be an easy link that we add to the website so that it is SUPER easy to know what to do.

**What kind of user are you?**
WID member (Administrator or ambassador on the site)

**Expected behavior**
Admins and Country Ambassadors login and will see a menu item called "Help" or "Support"
Need 1) a documentation website and 2) a nav item on the site itself

**Comment by pamelatech** [comment]
Nav is created, need to make DNS link to close this issue

**Comment by hlflanagan** [comment]
Site built; will need to iterate on documentation over time
