### ISSUE TITLE
Please include country on email footers address

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#51]
Can we include "UK" with the address on email footers? It doesn't currently pull through, despite it being in the Settings. Thanks

![image](https://user-images.githubusercontent.com/88625230/133069649-fbc6ca61-5965-45c2-aa98-91079de0eecd.png)
![image (1)](https://user-images.githubusercontent.com/88625230/133069653-6f15971d-492b-45f6-95b5-4f18ad565f63.png)

**Comment by mcresilkstart** [comment]
@fhobswid this has now been fixed and is active for the WiD site.  I checked the latest notification post and the 'UK@ country is included in the email footer.  Please check for yourself and then close this one if you agree.

**Comment by fhobswid** [comment]
Thanks @mcresilkstart
