### ISSUE TITLE
Accessing restricted pages requires login - then redirects to wrong page

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#53]
If a user is logged out and tries to access a page from the navigation (e.g. Jobs Board), this will take them to the Jobs Board in their home chapter.

I was on the apex homepage, clicked Jobs Board, was prompted to log in, logged in, got redirected to Global chapter Jobs Board (which doesn't have any content in it).

**Comment by fhobswid** [comment]
Noting a potential fix (untested) whereby full apex link (https://womeninidentity.silkstart.com/jobs) should be put into navigation, rather than just /jobs

**Comment by mcresilkstart** [comment]
@fhobswid I was trying to reproduce this problem.  If you are at the APEX and not logged in you are correctly asked to login if you access a restriced page like the jobs board.  Then once you do login you will always be directed to the HOME page of your home chapter (other than new member signup).  Note this doesn't take you to the chapter jobs board. From this chapter home page if you select the jobs board on the menu you will be redirected to the APEX jobs board so I don't see there is a problem.

Can you check please - maybe I am missing something in how you are reproducing this.

**Comment by fhobswid** [comment]
This is weird, it's actually working for me now. And it doesn't send me to my home chapter, it correctly redirects back to the apex jobs board. It definitely wasn't working yesterday... but seems to be now?! Perhaps @hlflanagan and @pamelatech could also give it a go just to check the result?

**Comment by hlflanagan** [comment]
Works as expected for me.
