### ISSUE TITLE
Email addressed referenced in TOS and privacy documentation must change to the correct value

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#54]
**Describe the bug**
There is an email mentioned in the privacy documentation that goes nowhere. 

**What kind of user are you?**
Any user on the site 

**To Reproduce**
1. Go to the footer and open the terms of service, look for @womeninidentity.org -  make sure all emails go to Debbie and one additional 

**Expected behavior**
An email sent to that address should succeed

**Comment by hlflanagan** [comment]
fixed
