### ISSUE TITLE
Metadata for Chapters is incorrect

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#59]
**Describe the bug**
When a link is emailed around, many email clients like outlook populate an image and metadata for the site.  Our Apex metadata looks great but our chapter metadata does not, it contains incorrect characters for punctuation etc.

Is this something we can edit ourselves?

**What kind of user are you?**
Any user receiving our site as a link in an email.

**To Reproduce**
1. Create an email that references both our main site, and our global chapter site
2. look at the different ways that a mail client like outlook renders the link (see screenshot)

**Expected behavior**
The chapters should look as good as the main site

**Screenshots**
![image](https://user-images.githubusercontent.com/2591320/133947440-f7247616-6712-43f6-9ba5-a28e5bc4ce77.png)
**Additional context**

**Comment by mcresilkstart** [comment]
@pamelatech you can edit the metadata yourself.  You find it by going to the Global home page and open it for editing and then select 'miscellaneous page options'  - there you will see a field 'meta page description' that has the text you are referencing.  It appears there is a problem with the Apostrophe in Identity's - it doesn't display this correctly with the Outlook test you tried.  Obviously you can re-word this to remove the apostrophe as a work around.  I will report this though as a problem.

**Comment by hlflanagan** [comment]
@mcresilkstart - I attempted to change the miscellaneous page option for each chapter page to say "Women in Identity: Global chapter - connect with members from across the globe." (where "Global" is changed as per chapter name) but the change did not save. (Steps: clicked on 'Edit this Page' then 'Options' then 'Miscellaneous Page Options' then updated Meta Page Description, then clicked Save)

**Comment by mcresilkstart** [comment]
@hlflanagan I assume you are updating the meta age description to remove the apostrophe that doesn't display correctly?  If so you must make sure that you publish the page for it to be the active page each time.

**Comment by mcresilkstart** [comment]
@hlflanagan I have updated all the chapter home page meta page descriptions with the new wording and published them.  Should be good now when they are rendered in a notification/email

**Comment by hlflanagan** [comment]
Thanks!
