### ISSUE TITLE
Events calendar (Global chapter only) to be populated - at least a few key events

### ISSUE THREAD

**Issue by fhobswid** [wid-tech/website#6]
Waiting on Thelma to send me a list to include - she has promised today, so hopefully will be able to populate it soon.

**Comment by fhobswid** [comment]
Have done some that Thelma sent over. Think Pam may have more she wants to add. Perhaps ambassadors can do some in training too.

**Comment by pamelatech** [comment]
This looks good for launch but we'll need an ongoing action
