### ISSUE TITLE
Need to show that there is a cost for new jobs board posts for non-sponsors

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#60]
**Describe the bug**
womeninidentity.silkstart.com/jobs/new does give any indication that there is a cost for posting new jobs by non-sponsors.

**What kind of user are you?**
Member

**To Reproduce**
1. Go to 'womeninidentity.silkstart.com/jobs/new'
2. Note that there are no indications the job post isn't free to post

**Expected behavior**
There should be something on the submission page if a non-sponsor is submitting the post that there will be a cost (exact cost TBD)

**Comment by mcresilkstart** [comment]
@hlflanagan  you are correct that there is nothing to warn a member creating a new job post that they may be charged.  I have added some example text that is above the job post button.  This is easy to edit (go to settings/apps/jobs and change the text displayed in RH column field.

If a charge is due (and this is setup to determine this based on member type) the user will be asked to pay for the listing after creating the job and prior to them being able to submit to an admin for approval - so they will find out later when they have to pay.

**Comment by hlflanagan** [comment]
This is helpful, and we've adjusted the text. We still think something is needed on the job submission page itself (https://www.womeninidentity.org/job/new), though. Is that possible?

**Comment by mcresilkstart** [comment]
@hlflanagan I can probably add some text to that submission page.  Can you give me the text that you want me to add and the preferred location on the page for this and I will try to ad?

**Comment by hlflanagan** [comment]
How about just putting "Fees apply for non-sponsors (£299 for a 30-day post)" below the header "Jobs" and above "New Jobs"?

**Comment by mcresilkstart** [comment]
@hlflanagan I have added this wording on the header of the job submission page.  I also updated it to the same text on the RHS of the job listing page and added it to the subheader of that page.  Let me know if you need any of this further adjusted/edited/formatted differently.  Note that these changes are on the APEX only at present.

**Comment by hlflanagan** [comment]
Awesome, thanks!
