### ISSUE TITLE
No community member access to Companies

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#61]
**Describe the bug**

**What kind of user are you?**
Not logged in/Guest, Member, Chapter Admin, Site Admin

**To Reproduce**
1. Login as unprivileged user
2. Click on Jobs Board
3. Click on Capital One

**Expected behavior**
Company profile should be visible to normal users

**Screenshots**
![image](https://user-images.githubusercontent.com/2591320/134010369-f2b2010b-0bb7-4956-9c3f-95535e909542.png)

**Additional context**

**Comment by mcresilkstart** [comment]
@pamelatech this is a permissions issue on the APEX.  I have just changed the permission grid to allow access to company details for member types:  community, country ambassador and friends of.  These member types can now access the company page from the jobs board listing in the example given.  Please check and also decide if any other 'user types' need to have this permission and I can add them

**Comment by hlflanagan** [comment]
Looks good to me. I tested as a community member.
