### ISSUE TITLE
13 Users failing import

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#63]
**Describe the bug**
13 Users have special characters in their name that are not importing into the system

**What kind of user are you?**
Users with fancy characters in their name

**To Reproduce**
Pam has the set of user names affected - for privacy reasons, they aren't listed here

**Expected behavior**
Umlauts and other special characters need to be represented for imported users.  Not sure if our original Website ever did this properly either but we want to make it work now.

**Additional context**

**Comment by hlflanagan** [comment]
Updated list submitted to @mcresilkstart

**Comment by mcresilkstart** [comment]
@hlflanagan @pamelatech thanks - that should fix it.  I will test again

**Comment by mcresilkstart** [comment]
@hlflanagan @pamelatech 13 member data now fixed - I ran another validation test and got no errors just loads of warnings which relate to the importer seeing some duplicates which will disappear when I clean the existing users out before running the import - but I won't do any more here until you give me the go-ahead

**Comment by pamelatech** [comment]
Yahoo!  We will run our last test shortly now that this issue is good and the email confirmation is complete
