### ISSUE TITLE
Jobs that have been deleted on the front end are archived in the back end

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#64]
**Describe the bug**
Jobs that are marked as "deleted" in the front end are marked as "archived" in the back end, and we don't know how to control how long a job is archived for. 

**What kind of user are you?**
Site Admin

**To Reproduce**
1. Go to 'https://www.womeninidentity.org/jobs?current_page=1&sort_type=featured_recent&filter=%7B%7D&display_type=default'
2. Click on 'Edit' for any job, and select 'delete"
3. Go to 'https://www.womeninidentity.org/onepage/jobs'
4. See jobs with a status of "archived"

**Expected behavior**
How long are jobs archived for? Where is that controlled?

**Comment by mcresilkstart** [comment]
@hlflanagan deleted jobs as you have found out go to archived status.  They will remain archived.  I can permanently delete them if you would like me to.  Just let me know.

**Comment by hlflanagan** [comment]
We're going create a new issue to request a default cleanup period as an RFE.
