### ISSUE TITLE
Google Analytics not configured

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#68]
**Describe the bug**
Google Analytics keys need to be set for each chapter and apex

**What kind of user are you?**
 Site Admin

**To Reproduce**
1. Go to https://apac.womeninidentity.org/onepage/network_config/website_settings or any other chapter's URL as admin
2. You should see a Google Analytics key set

**Expected behavior**
Google Analytics should be set up and the API should be heavily restricted.

**Comment by fhobswid** [comment]
GA is now tracking
