### ISSUE TITLE
Default color for webinar events appears to be white

### ISSUE THREAD

**Issue by hlflanagan** [wid-tech/website#72]
**Describe the bug**
The color for webinar events appears to be white, such that it can't be easily seen in the events calendar.

**What kind of user are you?**
Admin

**To Reproduce**
1. Go to 'https://global.womeninidentity.org/events'
2. Hover over October 7; you should barely see the IEEE Privacy event
3. Click on the event, URL =  'https://global.womeninidentity.org/events/ieee-digital-privacy-workshop'

**Expected behavior**
All events should show clearly on the events calendar

**Screenshots*
<img width="637" alt="Screen Shot 2021-10-02 at 9 04 50 AM" src="https://user-images.githubusercontent.com/4659093/135724098-e1706810-cce1-4043-8263-9222ff78b516.png">

**Comment by mcresilkstart** [comment]
@hlflanagan there was a problem with the colour setting for the default webinar event category.  I have changed it to something else.  The save action for this category is not saving so when you change the colour you have to then move to a different category and then it saves everything.  I will log a bug for this but you can work around it for now.  Perhaps @fhobswid would like to choose a more appropriate colour for this webinar category.

**Comment by fhobswid** [comment]
Hi @mcresilkstart I tried to change the webinar category colour to #2a693f - I tried the workaround suggested but it didn't work. Would you be able to update it for me please? Thanks

**Comment by mcresilkstart** [comment]
@fhobswid I eventually managed to change it but it required several attempts before it saved it correctly.  Should be ok now

**Comment by hlflanagan** [comment]
Thanks!
