### ISSUE TITLE
Email Subscription Preferences Lost in Import

### ISSUE THREAD

**Issue by pamelatech** [wid-tech/website#74]
**Describe the bug**
In the import, both members and contacts were subscribed to the newsletter subscription topic, however in our testing of the data import, it looks like all the members are now in "Not Subscribed" state.  This is an issue - some of our members have legitimately unsubscribed, and we need that status to be preserved, the rest should be subscribed.  We are migrating existing preferences and do not want those preferences changed

**What kind of user are you?**
Admin

**To Reproduce**
1. Go to the admin console 
2. Choose any member other than Heather, Francesca, or Pam
3. Open Email preferences
4. See email preference is "Not Subscribed"

**Expected behavior**
All members should have their previous subscription preferences preserved as per the data import file

**Screenshots**
![image](https://user-images.githubusercontent.com/2591320/135724867-f0ef5f11-778d-4ca0-ac52-1adb11842bc6.png)

**Additional context**

**Comment by mcresilkstart** [comment]
Can one of you delete the account that was imported from the import file
for ***@***.*** as I can't login now.  Once I get back
in I can investigate the 'unsubscribed' issue.  My first step will be to
check the subscriber status for the users that should be marked as
unsubscribed by looking in their home chapter not just at the APEX.

**Comment by mcresilkstart** [comment]
@pamelatech so the import process has imported the subscriber and group topics settings correctly in the APEX.  The global chapter (and any other chapter) have their own set of subscriber settings associated with that chapter.  So you can be a subscriber in the APEX but not in a chapter etc.  So if you run mailshots from the APEX then everything works fine as it is looking at the subscriber settings for members held at the APEX level.  If you run the mailshot from Global then it will use the global chapter subscriber settings for members of that chapter.  Given how you have decided to use the GLobal chapter I suspect you want to run mailshots from there and therefore need the subscriber settings to be set per the import file at the global chapter level.  If that is what you are looking for then I need to see if there is an easy way to get the subscriber settings 'copied across'.  Views?

**Comment by mcresilkstart** [comment]
@pamelatech the subscriber settings have now been imported at the GLobal chapter level so I think this now can be closed.

**Comment by pamelatech** [comment]
Successful!
